services:
  tor:
    image: docker.io/dockurr/tor
    container_name: tor
    volumes:
      - ./config:/etc/tor
      - ./tor_data:/var/lib/tor
    restart: always
    depends_on:
      setup-tor-pass:
        condition: service_completed_successfully
      nginx:
        condition: service_started
    network_mode: "service:nginx"


  # This is to set the password for the torctl
  # use to accsss `podman exec -it tor nyx`
  setup-tor-pass:
    image: docker.io/dockurr/tor
    container_name: setup-tor-pass
    environment:
      TOR_CTRL_PASS: "PASSWORD"
    volumes:
      - ./config:/etc/tor
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        set -eu
        sed -i '/^HashedControlPassword/d' /etc/tor/torrc
        echo "HashedControlPassword `tor --hash-password $TOR_CTRL_PASS`"  >> /etc/tor/torrc
    restart: "no"

  nginx:
    image: docker.io/nginx
    container_name: nginx
    depends_on:
      backend:
        condition: service_started
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "service:backend"

  # update this with a real backend app leave the service name as backend
  backend:
    image: docker.io/nginx
    container_name: backend

